# Generated by Django 4.2.7 on 2024-01-01 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="file",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="video.videocategory",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
