# Generated by Django 4.2.7 on 2024-01-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goaltracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="date_completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("quit", "Quit"),
                    ("completed", "Completed"),
                ],
                default="pending",
            ),
        ),
    ]
