# Generated by Django 4.2.7 on 2024-01-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "goaltracker",
            "0002_alter_goal_date_completed_alter_goal_is_completed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="goal",
            name="notes",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("quit", "Quit"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
