# Generated by Django 4.2.7 on 2024-01-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goaltracker", "0003_alter_goal_description_alter_goal_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="notes",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("quit", "Quit"),
                    ("completed", "Completed"),
                ],
                default="pending",
            ),
        ),
    ]
