# Generated by Django 4.2.7 on 2024-01-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dietplan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predefineddietplan",
            name="difficulty_level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("pro", "Pro")],
                max_length=255,
            ),
        ),
    ]
